In [2]:
%pip install recordlinkage

Note: you may need to restart the kernel to use updated packages.

  DEPRECATION: jellyfish is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Collecting recordlinkage
  Downloading recordlinkage-0.15-py3-none-any.whl (926 kB)
     ---------------------------------------- 0.0/926.5 kB ? eta -:--:--
     --- ----------------------------------- 81.9/926.5 kB 2.2 MB/s eta 0:00:01
     ------- ------------------------------ 194.6/926.5 kB 2.3 MB/s eta 0:00:01
     ------------ ------------------------- 307.2/926.5 kB 2.1 MB/s eta 0:00:01
     ---------------- --------------------- 409.6/926.5 kB 2.3 MB/s eta 0:00:01
     --------------------- ---------------- 522.2/926.5 kB 2.2 MB/s eta 0:00:01
     ------------------------- ------------ 624.6/926.5 kB 2.2 MB/s eta 0:00:01
     ----------------------------- -------- 727.0/926.5 kB 2.3 MB/s eta 0:00:01
     ---------------------------------- --- 829.4/926.5 kB 2.3 MB/s eta 0:00:01
     -------------------------------------  921.6/926.5 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 926.5/926.5 kB 2.1 MB/s eta 0:00:00
Collecting jellyfish>=0.8.0
  Downloading jellyfish-0.9.0.tar.gz (132 kB)
     ---------------------------------------- 0.0/132.6 kB ? eta -:--:--
     -------------------------------- ----- 112.6/132.6 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 132.6/132.6 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.13.0 in c:\python311\lib\site-packages (from recordlinkage) (1.24.2)
Collecting pandas<2,>=1
  Using cached pandas-1.5.3-cp311-cp311-win_amd64.whl (10.3 MB)
Collecting scipy>=1
  Using cached scipy-1.10.0-cp311-cp311-win_amd64.whl (42.2 MB)
Collecting scikit-learn>=0.19.0
  Downloading scikit_learn-1.2.1-cp311-cp311-win_amd64.whl (8.2 MB)
     ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
     ---------------------------------------- 0.1/8.2 MB 1.1 MB/s eta 0:00:08
      --------------------------------------- 0.2/8.2 MB 2.4 MB/s eta 0:00:04
     - -------------------------------------- 0.3/8.2 MB 2.2 MB/s eta 0:00:04
     - -------------------------------------- 0.4/8.2 MB 2.2 MB/s eta 0:00:04
     -- ------------------------------------- 0.5/8.2 MB 2.3 MB/s eta 0:00:04
     -- ------------------------------------- 0.6/8.2 MB 2.3 MB/s eta 0:00:04
     --- ------------------------------------ 0.7/8.2 MB 2.2 MB/s eta 0:00:04
     --- ------------------------------------ 0.8/8.2 MB 2.2 MB/s eta 0:00:04
     ---- ----------------------------------- 0.9/8.2 MB 2.2 MB/s eta 0:00:04
     ---- ----------------------------------- 1.0/8.2 MB 2.2 MB/s eta 0:00:04
     ----- ---------------------------------- 1.1/8.2 MB 2.2 MB/s eta 0:00:04
     ----- ---------------------------------- 1.2/8.2 MB 2.2 MB/s eta 0:00:04
     ------ --------------------------------- 1.4/8.2 MB 2.3 MB/s eta 0:00:04
     ------ --------------------------------- 1.4/8.2 MB 2.2 MB/s eta 0:00:04
     ------- -------------------------------- 1.5/8.2 MB 2.2 MB/s eta 0:00:03
     -------- ------------------------------- 1.7/8.2 MB 2.2 MB/s eta 0:00:03
     -------- ------------------------------- 1.8/8.2 MB 2.2 MB/s eta 0:00:03
     -------- ------------------------------- 1.9/8.2 MB 2.2 MB/s eta 0:00:03
     -------- ------------------------------- 1.9/8.2 MB 2.2 MB/s eta 0:00:03
     --------- ------------------------------ 2.0/8.2 MB 2.2 MB/s eta 0:00:03
     ---------- ----------------------------- 2.2/8.2 MB 2.2 MB/s eta 0:00:03
     ---------- ----------------------------- 2.3/8.2 MB 2.2 MB/s eta 0:00:03
     ----------- ---------------------------- 2.4/8.2 MB 2.2 MB/s eta 0:00:03
     ----------- ---------------------------- 2.5/8.2 MB 2.2 MB/s eta 0:00:03
     ------------ --------------------------- 2.6/8.2 MB 2.2 MB/s eta 0:00:03
     ------------- -------------------------- 2.7/8.2 MB 2.2 MB/s eta 0:00:03
     ------------- -------------------------- 2.8/8.2 MB 2.2 MB/s eta 0:00:03
     -------------- ------------------------- 2.9/8.2 MB 2.2 MB/s eta 0:00:03
     -------------- ------------------------- 3.0/8.2 MB 2.2 MB/s eta 0:00:03
     --------------- ------------------------ 3.1/8.2 MB 2.2 MB/s eta 0:00:03
     --------------- ------------------------ 3.2/8.2 MB 2.2 MB/s eta 0:00:03
     ---------------- ----------------------- 3.3/8.2 MB 2.2 MB/s eta 0:00:03
     ---------------- ----------------------- 3.4/8.2 MB 2.2 MB/s eta 0:00:03
     ----------------- ---------------------- 3.5/8.2 MB 2.2 MB/s eta 0:00:03
     ----------------- ---------------------- 3.6/8.2 MB 2.2 MB/s eta 0:00:03
     ------------------ --------------------- 3.7/8.2 MB 2.2 MB/s eta 0:00:03
     ------------------ --------------------- 3.8/8.2 MB 2.2 MB/s eta 0:00:02
     ------------------- -------------------- 3.9/8.2 MB 2.2 MB/s eta 0:00:02
     ------------------- -------------------- 4.0/8.2 MB 2.2 MB/s eta 0:00:02
     -------------------- ------------------- 4.1/8.2 MB 2.2 MB/s eta 0:00:02
     -------------------- ------------------- 4.3/8.2 MB 2.2 MB/s eta 0:00:02
     --------------------- ------------------ 4.4/8.2 MB 2.2 MB/s eta 0:00:02
     --------------------- ------------------ 4.5/8.2 MB 2.2 MB/s eta 0:00:02
     ---------------------- ----------------- 4.6/8.2 MB 2.2 MB/s eta 0:00:02
     ---------------------- ----------------- 4.7/8.2 MB 2.2 MB/s eta 0:00:02
     ----------------------- ---------------- 4.8/8.2 MB 2.2 MB/s eta 0:00:02
     ----------------------- ---------------- 4.9/8.2 MB 2.2 MB/s eta 0:00:02
     ------------------------ --------------- 5.0/8.2 MB 2.2 MB/s eta 0:00:02
     ------------------------ --------------- 5.1/8.2 MB 2.3 MB/s eta 0:00:02
     ------------------------- -------------- 5.2/8.2 MB 2.2 MB/s eta 0:00:02
     ------------------------- -------------- 5.3/8.2 MB 2.2 MB/s eta 0:00:02
     -------------------------- ------------- 5.4/8.2 MB 2.2 MB/s eta 0:00:02
     -------------------------- ------------- 5.5/8.2 MB 2.3 MB/s eta 0:00:02
     --------------------------- ------------ 5.6/8.2 MB 2.2 MB/s eta 0:00:02
     --------------------------- ------------ 5.8/8.2 MB 2.2 MB/s eta 0:00:02
     ---------------------------- ----------- 5.8/8.2 MB 2.2 MB/s eta 0:00:02
     ----------------------------- ---------- 6.0/8.2 MB 2.2 MB/s eta 0:00:02
     ----------------------------- ---------- 6.1/8.2 MB 2.3 MB/s eta 0:00:01
     ------------------------------ --------- 6.2/8.2 MB 2.2 MB/s eta 0:00:01
     ------------------------------ --------- 6.3/8.2 MB 2.3 MB/s eta 0:00:01
     ------------------------------- -------- 6.4/8.2 MB 2.2 MB/s eta 0:00:01
     ------------------------------- -------- 6.5/8.2 MB 2.2 MB/s eta 0:00:01
     -------------------------------- ------- 6.6/8.2 MB 2.3 MB/s eta 0:00:01
     -------------------------------- ------- 6.7/8.2 MB 2.2 MB/s eta 0:00:01
     --------------------------------- ------ 6.8/8.2 MB 2.3 MB/s eta 0:00:01
     --------------------------------- ------ 6.9/8.2 MB 2.2 MB/s eta 0:00:01
     ---------------------------------- ----- 7.0/8.2 MB 2.2 MB/s eta 0:00:01
     ---------------------------------- ----- 7.1/8.2 MB 2.2 MB/s eta 0:00:01
     ----------------------------------- ---- 7.2/8.2 MB 2.2 MB/s eta 0:00:01
     ----------------------------------- ---- 7.3/8.2 MB 2.3 MB/s eta 0:00:01
     ------------------------------------ --- 7.5/8.2 MB 2.2 MB/s eta 0:00:01
     ------------------------------------ --- 7.6/8.2 MB 2.2 MB/s eta 0:00:01
     ------------------------------------- -- 7.7/8.2 MB 2.3 MB/s eta 0:00:01
     ------------------------------------- -- 7.8/8.2 MB 2.3 MB/s eta 0:00:01
     -------------------------------------- - 7.9/8.2 MB 2.3 MB/s eta 0:00:01
     -------------------------------------- - 8.0/8.2 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------  8.1/8.2 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------  8.2/8.2 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------  8.2/8.2 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------- 8.2/8.2 MB 2.2 MB/s eta 0:00:00
Collecting joblib
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\andre\appdata\roaming\python\python311\site-packages (from pandas<2,>=1->recordlinkage) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\python311\lib\site-packages (from pandas<2,>=1->recordlinkage) (2022.7.1)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in c:\users\andre\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.1->pandas<2,>=1->recordlinkage) (1.16.0)
Installing collected packages: threadpoolctl, scipy, joblib, jellyfish, scikit-learn, pandas, recordlinkage
  Running setup.py install for jellyfish: started
  Running setup.py install for jellyfish: finished with status 'done'
Successfully installed jellyfish-0.9.0 joblib-1.2.0 pandas-1.5.3 recordlinkage-0.15 scikit-learn-1.2.1 scipy-1.10.0 threadpoolctl-3.1.0

In [2]:
import recordlinkage
import pandas as pd

In [3]:
df = pd.read_json('output_alignment_multithread_finalpass/schema_mediato.json')
print(len(df))

# half_size = int(len(df)/2)
# df_a = df.iloc[:half_size,:]
# df_b = df.iloc[half_size:,:]

df_a = df
df_b = df

display(df_a)
display(df_b)

198615

,name,industry,market_cap,employees,country,headquarters,address,sector,ceo,founded,founders,share_price,website,stock,area_served,revenue
0,None,Artificial intelligence,None,None,China,None,None,None,None,None,None,None,None,None,None,None
1,None,Other,None,None,United States,None,None,None,None,None,None,None,None,None,None,None
2,None,E-commerce & direct-to-consumer,None,None,China,None,None,None,None,None,None,None,None,None,None,None
3,None,Fintech,None,None,United States,None,None,None,None,None,None,None,None,None,None,None
4,None,Internet software & services,None,None,Australia,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198610,\n Olajide Semi...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198611,\n Kaidi Klein\...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198612,\n Liridon Resh...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198613,\n Margus L\xc3...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198614,\n Hannes Rosin...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

,name,industry,market_cap,employees,country,headquarters,address,sector,ceo,founded,founders,share_price,website,stock,area_served,revenue
0,None,Artificial intelligence,None,None,China,None,None,None,None,None,None,None,None,None,None,None
1,None,Other,None,None,United States,None,None,None,None,None,None,None,None,None,None,None
2,None,E-commerce & direct-to-consumer,None,None,China,None,None,None,None,None,None,None,None,None,None,None
3,None,Fintech,None,None,United States,None,None,None,None,None,None,None,None,None,None,None
4,None,Internet software & services,None,None,Australia,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198610,\n Olajide Semi...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198611,\n Kaidi Klein\...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198612,\n Liridon Resh...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198613,\n Margus L\xc3...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
198614,\n Hannes Rosin...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [26]:
print(df[df.index == 1202]['name'])
print(df[df.index == 1202]['name'].values[0])

1202    Apple
Name: name, dtype: object
Apple

In [4]:
indexer = recordlinkage.Index()
indexer.block('name')
candidate_links = indexer.index(df_a, df_b)

print(candidate_links)

MultiIndex([(  1202,   1202),
            (  1202,   7104),
            (  1202,   8099),
            (  1202,  16099),
            (  1202,  23192),
            (  1202,  25046),
            (  1202,  40045),
            (  1202,  49100),
            (  1202,  59782),
            (  1202,  67005),
            ...
            (198603, 198603),
            (198605, 198605),
            (198606, 198606),
            (198607, 198607),
            (198608, 198608),
            (198609, 198609),
            (198610, 198610),
            (198611, 198611),
            (198612, 198612),
            (198613, 198613)],
           length=916434)

In [5]:
set_no_copy = set()
for (c,b) in candidate_links:
    if (b,c) not in set_no_copy and (c != b):
        set_no_copy.add((c,b))

print(len(set_no_copy))

list_no_copy = list(set_no_copy)
# gli elementi delle coppie vengono distribuite su due liste parallele
list_0 = [x[0] for x in list_no_copy]
list_1 = [x[1] for x in list_no_copy]

362257

In [6]:
multi_index = pd.MultiIndex.from_arrays([list_0, list_1])

In [7]:
print(multi_index)

MultiIndex([( 16914,  53017),
            ( 96199, 150619),
            ( 48460, 141092),
            ( 76166, 186366),
            ( 25075, 101547),
            ( 55814, 105606),
            ( 91775, 157193),
            ( 20651, 123205),
            (119755, 139657),
            (101835, 186271),
            ...
            (151583, 162585),
            ( 90760, 167186),
            (160670, 171680),
            (124224, 188318),
            (186715, 186771),
            (  1322,   8235),
            ( 87684, 178903),
            ( 24107,  84941),
            (  5010,  13297),
            ( 20528,  79822)],
           length=362257)

In [8]:
compare = recordlinkage.Compare()

compare.string('name', 'name', method='jarowinkler', threshold=0.5)
# compare.string('industry', 'industry', method='jarowinkler', threshold=0.85)
compare.string('country', 'country', method='jarowinkler', threshold=0.5)
compare.string('headquarters', 'country', method='jarowinkler', threshold=0.5)
# compare.string('country', 'headquarters', method='jarowinkler', threshold=0.5)
# compare.string('headquarters', 'headquarters', method='jarowinkler', threshold=0.5)


# compare.string('headquarters', 'headquarters', method='jarowinkler', threshold=0.85)
# compare.string('ceo', 'ceo', method='jarowinkler', threshold=0.85)
# compare.string('sector', 'sector', method='jarowinkler', threshold=0.85)

# The comparison vectors
compare_vectors = compare.compute(candidate_links, df_a, df_b)
print(compare_vectors)
type(compare_vectors)

                 0    1    2
1202   1202    1.0  1.0  0.0
       7104    1.0  0.0  0.0
       8099    1.0  1.0  0.0
       16099   1.0  1.0  0.0
       23192   1.0  0.0  0.0
...            ...  ...  ...
198609 198609  1.0  0.0  0.0
198610 198610  1.0  0.0  0.0
198611 198611  1.0  0.0  0.0
198612 198612  1.0  0.0  0.0
198613 198613  1.0  0.0  0.0

[916434 rows x 3 columns]

pandas.core.frame.DataFrame

In [9]:
compare_vectors = compare_vectors[compare_vectors.index.isin(multi_index)]
display(compare_vectors)

                 0    1    2
1202   7104    1.0  0.0  0.0
       8099    1.0  1.0  0.0
       16099   1.0  1.0  0.0
       23192   1.0  0.0  0.0
       25046   1.0  0.0  0.0
...            ...  ...  ...
198440 198450  1.0  0.0  0.0
       198451  1.0  0.0  0.0
198450 198451  1.0  0.0  0.0
198454 198584  1.0  0.0  0.0
198527 198528  1.0  0.0  0.0

[362257 rows x 3 columns]

In [10]:
ecm = recordlinkage.ECMClassifier()
matches = ecm.fit_predict(compare_vectors)

In [11]:
print(type(matches))
print(matches)
print(len(list(matches)))

<class 'pandas.core.indexes.multi.MultiIndex'>
MultiIndex([(  1202,   8099),
            (  1202,  16099),
            (  1202,  75945),
            (  1202, 101476),
            (  1202, 119575),
            (  1202, 187253),
            (  8099,  16099),
            (  8099,  75945),
            (  8099, 101476),
            (  8099, 119575),
            ...
            (192576, 194569),
            (192579, 194572),
            (192582, 194578),
            (192585, 194581),
            (192588, 194584),
            (192591, 194587),
            (192594, 194593),
            (192600, 192606),
            (192878, 192881),
            (193017, 193020)],
           length=160404)
160404

In [12]:
dict_matches = {}
keyToIgnore = set()
for k, v in matches:
    if k in keyToIgnore:
        continue
    elif k in dict_matches.keys():
        dict_matches[k].append(v)
        keyToIgnore.add(v)
    else :
        dict_matches[k] = [v]
        keyToIgnore.add(v)

In [14]:
# keyToIgnore
print(dict_matches)
print(len(dict_matches.keys()))

TypeError: unhashable type: 'slice'

In [21]:
import csv
import time

start = time.time()

df_match = pd.DataFrame(columns=['label','left_id', 'left_name' , 'left_industry', 'left_market_cap', 'left_employees', 'left_country', 'left_headquarters', 'left_address', 'left_sector', 'left_ceo', 'left_founded', 'left_founders', 'left_share_price', 'left_website', 'left_stock', 'left_area_served', 'left_revenue', 'right_id','right_name' , 'right_industry', 'right_market_cap', 'right_employees', 'right_country', 'right_headquarters', 'right_address', 'right_sector', 'right_ceo', 'right_founded', 'right_founders', 'right_share_price', 'right_website', 'right_stock', 'right_area_served', 'right_revenue'])
for k in dict_matches.keys():
    for v in dict_matches[k]:
        df_match.loc[len(df_match.index)] = ([1, k, df[df.index == k]['name'].values[0] , df[df.index == k]['industry'].values[0], df[df.index == k]['market_cap'].values[0], df[df.index == k]['employees'].values[0], df[df.index == k]['country'].values[0], df[df.index == k]['headquarters'].values[0], df[df.index == k]['address'].values[0], df[df.index == k]['sector'].values[0], df[df.index == k]['ceo'].values[0], df[df.index == k]['founded'].values[0], df[df.index == k]['founders'].values[0], df[df.index == k]['share_price'].values[0], df[df.index == k]['website'].values[0], df[df.index == k]['stock'].values[0], df[df.index == k]['area_served'].values[0], df[df.index == k]['revenue'].values[0], v, df[df.index == v]['name'].values[0], df[df.index == v]['industry'].values[0], df[df.index == v]['market_cap'].values[0], df[df.index == v]['employees'].values[0], df[df.index == v]['country'].values[0], df[df.index == v]['headquarters'].values[0], df[df.index == v]['address'].values[0], df[df.index == v]['sector'].values[0], df[df.index == v]['ceo'].values[0], df[df.index == v]['founded'].values[0], df[df.index == v]['founders'].values[0], df[df.index == v]['share_price'].values[0], df[df.index == v]['website'].values[0], df[df.index == v]['stock'].values[0], df[df.index == v]['area_served'].values[0], df[df.index == v]['revenue'].values[0]])
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

The time of execution of above program is : 7204225.497484207 ms

In [22]:
df_match.to_csv('output_match/df_match.csv')

In [77]:
prova1 = df.iloc[769,:]
prova2 = df.iloc[1269,:]
display(prova1)
display(prova2)

name                BASF SE
industry               None
market_cap      68991000000
employees            110302
country                None
headquarters        Germany
address                None
sector                 None
ceo
founded                None
founders                NaN
share_price             NaN
website                None
stock                  None
area_served             NaN
revenue         86615000000
Name: 769, dtype: object

name                       BASF SE
industry                      None
market_cap      70.978 Billion USD
employees                     None
country                    Germany
headquarters                  None
address                       None
sector                        None
ceo                           None
founded                       None
founders                       NaN
share_price                    NaN
website                       None
stock                         None
area_served                    NaN
revenue                       None
Name: 1269, dtype: object